const fs = require('fs');
const path = require('path');

const dir = path.join(__dirname, 'components', 'shared', 'SecretariaFlutuanteV2');
const filesToProcess = [
    'elena-prompt.ts',
    'SecretariaFlutuante.tsx',
    'useElenaSalvar.ts',
    'useElenaSession.ts',
    'useElenaOffline.ts',
    'elena-types.ts',
    'elena-constants.ts'
];

const replacements = {
    'dinÃ¢mico': 'dinâmico',
    'utilitÃ¡rios': 'utilitários',
    'formataÃ§Ã£o': 'formatação',
    'VocÃª': 'Você',
    'vocÃª': 'você',
    'Ã©': 'é',
    'SecretÃ¡ria': 'Secretária',
    'comunicaÃ§Ã£o': 'comunicação',
    'BrasÃ\xadlia': 'Brasília',
    'MÃŠS': 'MÊS',
    'mÃªs': 'mês',
    'sÃ¡bado': 'sábado',
    'terÃ§a-feira': 'terça-feira',
    'INÃ\x8dCIO': 'INÍCIO',
    'inÃ\xadcio': 'início',
    'prÃ³ximo': 'próximo',
    'PRÃ“XIMOS': 'PRÓXIMOS',
    'cartÃ£o': 'cartão',
    'CARTÃƒO': 'CARTÃO',
    'ReuniÃ£o': 'Reunião',
    'AlmoÃ§o': 'Almoço',
    'escritÃ³rio': 'escritório',
    'ServiÃ§o': 'Serviço',
    'informaÃ§Ã£o': 'informação',
    'RelatÃ³rio': 'Relatório',
    'RELATÃ“RIO': 'RELATÓRIO',
    'OcorrÃªncia': 'Ocorrência',
    'OCORRÃŠNCIA': 'OCORRÊNCIA',
    'TransferÃªncia': 'Transferência',
    'TRANSFERÃŠNCIA': 'TRANSFERÊNCIA',
    'aÃ§Ã£o': 'ação',
    'AÃ§Ã£o': 'Ação',
    'AÃ‡ÃƒO': 'AÇÃO',
    'exibiÃ§Ã£o': 'exibição',
    'invÃ¡lido': 'inválido',
    'genÃ©rico': 'genérico',
    'Ãºltimo': 'último',
    'ÃšLTIMO': 'ÚLTIMO',
    'Ãšltimo': 'Último',
    'Ãºnica': 'única',
    'ÃšNICA': 'ÚNICA',
    'SÃ\x8dNTESE': 'SÍNTESE',
    'SÃ³': 'Só',
    'sÃ³': 'só',
    'AtÃ©': 'Até',
    'atÃ©': 'até',
    'JÃ¡': 'Já',
    'jÃ¡': 'já',
    'NÃƒO': 'NÃO',
    'nÃ£o': 'não',
    'NÃ£o': 'Não',
    'Ã\x81UDIO': 'ÁUDIO',
    'Ã¡udio': 'áudio',
    'Ã\x8dCONE': 'ÍCONE',
    'Ã\xadcone': 'ícone',
    'Ã“BVIAS': 'ÓBVIAS',
    'Ã³bvio': 'óbvio',
    'CÃ“DIGO': 'CÓDIGO',
    'cÃ³digo': 'código',
    'DÃšVIDA': 'DÚVIDA',
    'dÃºvida': 'dúvida',
    'Ã\x81REA': 'ÁREA',
    'Ã¡rea': 'área',
    'Ã‰': 'É',
    'Ã©': 'é',
    'VocÃªs': 'Vocês',
    'vocÃªs': 'vocês',
    'trÃªs': 'três',
    'TÃ\x8dTULO': 'TÍTULO',
    'tÃ\xadtulo': 'título',
    'PadrÃ£o': 'Padrão',
    'padrÃ£o': 'padrão',
    'PadrÃµes': 'Padrões',
    'padrÃµes': 'padrões',
    'Ã\x8dndice': 'Índice',
    'Ã\xadndice': 'índice',
    'FÃ\xadSICA': 'FÍSICA',
    'fÃ\xadsica': 'física',
    'MÃºltiplos': 'Múltiplos',
    'mÃºltiplos': 'múltiplos',
    'MÃšLTIPLOS': 'MÚLTIPLOS',
    'Ã€': 'À',
    'Ã\xa0': 'à',
    'Ã\xa0s': 'às',
    'Ã\x81s': 'Às',
    'Ã\xa1s': 'ás',
    'SIMULTÃ‚NEOS': 'SIMULTÂNEOS',
    'simultÃ¢neos': 'simultâneos',
    'Ã“RGÃƒO': 'ÓRGÃO',
    'Ã³rgÃ£o': 'órgão',
    'OBRIGATÃ“RIA': 'OBRIGATÓRIA',
    'obrigatÃ³ria': 'obrigatória',
    'OBRIGATÃ“RIO': 'OBRIGATÓRIO',
    'obrigatÃ³rio': 'obrigatório',
    'ÃšNICO': 'ÚNICO',
    'Ãºnico': 'único',
    'ÃšLTIMOS': 'ÚLTIMOS',
    'Ãºltimos': 'últimos',
    'Ãšltimos': 'Últimos',
    'Ã£': 'ã',
    'Ã§': 'ç',
    'Ã¡': 'á',
    'Ã³': 'ó',
    'Ã\xad': 'í',
    'Ãª': 'ê',
    'Ã¢': 'â',
    'Ãµ': 'õ',
    'Ãº': 'ú',
    'Ã€': 'À',
    'Ã\x81': 'Á',
    'Ã‰': 'É',
    'Ã“': 'Ó',
    'Ã\x8d': 'Í',
    'Ã‡': 'Ç',
    'â€”': '—',
    'ðŸ§\x80': '🧠',
    'ðŸ’°': '💰',
    'âš\xa0ï¸\x8f': '⚠️',
    'ðŸ“\x90': '📌',
    'ðŸ“…': '📅',
    'â\x8f°': '⏰',
    'ðŸ’³': '💳',
    'âœ…': '✅',
    'ðŸ\x8f¢': '🏢',
    'ðŸ’¸': '💸',
    'ðŸ’¡': '💡',
    'ðŸ“‹': '📋',
    'ðŸ—‚ï¸\x8f': '🗂️',
    'ðŸ“ˆ': '📈',
    'ðŸ”„': '🔄',
    'â\x9dŒ': '❌',
    'ðŸŽ¯': '🎯',
    'ðŸ‘¥': '👥',
    'ðŸ“Š': '📊',
    'ðŸ\x8f¦': '🏦',
    'â\xad\x90': '⭐',
    'ðŸ“ž': '📞',
    'ðŸ¤\x9d': '🤝',
    'ðŸ‘¤': '👤',
    'ðŸ”Ž': '🔍',
    'âœ\x8fï¸\x8f': '✏️',
    'USUÃ\x81RIO': 'USUÁRIO',
    'SÃ\x8dNTESE': 'SÍNTESE',
    'SÃ³': 'Só',
    'sÃ³': 'só',
    'AtÃ©': 'Até',
    'atÃ©': 'até',
    'JÃ¡': 'Já',
    'jÃ¡': 'já',
    'NÃƒO': 'NÃO',
    'nÃ£o': 'não',
    'NÃ£o': 'Não',
    'Ã\x81UDIO': 'ÁUDIO',
    'Ã¡udio': 'áudio',
    'Ã\x8dCONE': 'ÍCONE',
    'Ã\xadcone': 'ícone',
    'Ã“BVIAS': 'ÓBVIAS',
    'Ã³bvio': 'óbvio',
    'CÃ“DIGO': 'CÓDIGO',
    'cÃ³digo': 'código',
    'DÃšVIDA': 'DÚVIDA',
    'dÃºvida': 'dúvida',
    'Ã\x81REA': 'ÁREA',
    'Ã¡rea': 'área',
    'Ã‰': 'É',
    'Ã©': 'é',
    'VocÃªs': 'Vocês',
    'vocÃªs': 'vocês',
    'trÃªs': 'três',
    'TÃ\x8dTULO': 'TÍTULO',
    'tÃ\xadtulo': 'título',
    'PadrÃ£o': 'Padrão',
    'padrÃ£o': 'padrão',
    'PadrÃµes': 'Padrões',
    'padrÃµes': 'padrões',
    'Ã\x8dndice': 'Índice',
    'Ã\xadndice': 'índice',
    'FÃ\xadSICA': 'FÍSICA',
    'fÃ\xadsica': 'física',
    'MÃºltiplos': 'Múltiplos',
    'mÃºltiplos': 'múltiplos',
    'MÃšLTIPLOS': 'MÚLTIPLOS',
    'Ã€': 'À',
    'Ã\xa0': 'à',
    'Ã\xa0s': 'às',
    'Ã\x81s': 'Às',
    'Ã\xa1s': 'ás',
    'SIMULTÃ‚NEOS': 'SIMULTÂNEOS',
    'simultÃ¢neos': 'simultâneos',
    'Ã“RGÃƒO': 'ÓRGÃO',
    'Ã³rgÃ£o': 'órgão',
    'OBRIGATÃ“RIA': 'OBRIGATÓRIA',
    'obrigatÃ³ria': 'obrigatória',
    'OBRIGATÃ“RIO': 'OBRIGATÓRIO',
    'obrigatÃ³rio': 'obrigatório',
    'ÃšNICO': 'ÚNICO',
    'Ãºnico': 'único',
    'ÃšLTIMOS': 'ÚLTIMOS',
    'Ãºltimos': 'últimos',
    'Ãšltimos': 'Últimos',
    'MÃªs': 'Mês',
    'mÃªs': 'mês',
    'Ãªs': 'ês',
    'Ãªncia': 'ência',
    'ReferÃªncia': 'Referência',
    'referÃªncia': 'referência'
};

filesToProcess.forEach(file => {
    const filepath = path.join(dir, file);
    if (!fs.existsSync(filepath)) return;
    let text = fs.readFileSync(filepath, 'utf8');

    for (const [k, v] of Object.entries(replacements)) {
        text = text.split(k).join(v);
    }
    
    // Fallback pra bytes
    const buf = Buffer.from(text, 'utf8');
    try {
        const decoded = buf.toString('latin1');
        // Check if there are still any weird chars
    } catch(e) {}

    fs.writeFileSync(filepath, text, 'utf8');
    console.log('Processed', file);
});

// Outros diretórios
const backendDir = path.join(__dirname, 'cajado-backend', 'src', 'routes');
if (fs.existsSync(backendDir)) {
    const files = fs.readdirSync(backendDir);
    files.forEach(f => {
        const filepath = path.join(backendDir, f);
        if (f.endsWith('.js') && fs.existsSync(filepath)) {
            let text = fs.readFileSync(filepath, 'utf8');
            for (const [k, v] of Object.entries(replacements)) {
                text = text.split(k).join(v);
            }
            fs.writeFileSync(filepath, text, 'utf8');
        }
    });
}
