-- ============================================================
-- SISTEMA CAJADO - MIGRATION 052
-- NOTA: O cron job NÃO usa pg_cron (não disponível no Supabase Free).
-- Em vez disso, o Railway chama a rota /api/cron/send-push a cada minuto.
--
-- Configuração no Railway:
-- 1. No serviço "scintillating-freedom" (cron worker), configurar:
--    curl https://sistema.cajadosolucoes.com/api/cron/send-push?secret=$CRON_SECRET
-- 2. Ou usar o Railway Cron Job com schedule "* * * * *"
--
-- A rota /api/cron/send-push chama a Edge Function send-push do Supabase
-- que verifica eventos na janela -1 a +5 min e envia push notifications.
-- ============================================================

-- A extensão pg_net pode ser útil para outras integrações
CREATE EXTENSION IF NOT EXISTS pg_net;

-- O cron job via pg_cron foi substituído pelo Railway cron.
-- Código original mantido como referência (comentado):
--
-- SELECT cron.schedule(
--   'send-push-alerts',
--   '* * * * *',
--   $$
--   SELECT net.http_post(
--     url     := 'https://wagkyyqstsgetktefewd.supabase.co/functions/v1/send-push',
--     headers := jsonb_build_object(
--       'Content-Type',  'application/json',
--       'Authorization', 'Bearer <anon-key>'
--     ),
--     body    := '{}'::jsonb
--   );
--   $$
-- );
